import { mirrorNodeDefinitions } from "./registry";

export const mirrorNodeKeys = {
  account: {
    info: mirrorNodeDefinitions.account.info.buildKey,
    balances: mirrorNodeDefinitions.account.balances.buildKey,
    tokens: mirrorNodeDefinitions.account.tokens.buildKey,
    nfts: mirrorNodeDefinitions.account.nfts.buildKey,
    stakingRewards: mirrorNodeDefinitions.account.stakingRewards.buildKey,
    cryptoAllowances: mirrorNodeDefinitions.account.cryptoAllowances.buildKey,
    tokenAllowances: mirrorNodeDefinitions.account.tokenAllowances.buildKey,
    nftAllowances: mirrorNodeDefinitions.account.nftAllowances.buildKey,
    outstandingAirdrops: mirrorNodeDefinitions.account.outstandingAirdrops.buildKey,
    pendingAirdrops: mirrorNodeDefinitions.account.pendingAirdrops.buildKey,
    list: mirrorNodeDefinitions.account.list.buildKey,
  },
  token: {
    info: mirrorNodeDefinitions.token.info.buildKey,
    balances: mirrorNodeDefinitions.token.balances.buildKey,
    balancesSnapshot: mirrorNodeDefinitions.token.balancesSnapshot.buildKey,
    nfts: mirrorNodeDefinitions.token.nfts.buildKey,
    nft: mirrorNodeDefinitions.token.nft.buildKey,
    nftTransactions: mirrorNodeDefinitions.token.nftTransactions.buildKey,
    list: mirrorNodeDefinitions.token.list.buildKey,
  },
  contract: {
    info: mirrorNodeDefinitions.contract.info.buildKey,
    results: mirrorNodeDefinitions.contract.results.buildKey,
    result: mirrorNodeDefinitions.contract.result.buildKey,
    state: mirrorNodeDefinitions.contract.state.buildKey,
    logs: mirrorNodeDefinitions.contract.logs.buildKey,
    allResults: mirrorNodeDefinitions.contract.allResults.buildKey,
    resultByTx: mirrorNodeDefinitions.contract.resultByTx.buildKey,
    resultActions: mirrorNodeDefinitions.contract.resultActions.buildKey,
    resultOpcodes: mirrorNodeDefinitions.contract.resultOpcodes.buildKey,
    allLogs: mirrorNodeDefinitions.contract.allLogs.buildKey,
    call: mirrorNodeDefinitions.contract.call.buildKey,
    list: mirrorNodeDefinitions.contract.list.buildKey,
  },
  transaction: {
    info: mirrorNodeDefinitions.transaction.info.buildKey,
    byAccount: mirrorNodeDefinitions.transaction.byAccount.buildKey,
    list: mirrorNodeDefinitions.transaction.list.buildKey,
  },
  topic: {
    info: mirrorNodeDefinitions.topic.info.buildKey,
    messages: mirrorNodeDefinitions.topic.messages.buildKey,
    message: mirrorNodeDefinitions.topic.message.buildKey,
    messageByTimestamp: mirrorNodeDefinitions.topic.messageByTimestamp.buildKey,
    list: mirrorNodeDefinitions.topic.list.buildKey,
  },
  schedule: {
    info: mirrorNodeDefinitions.schedule.info.buildKey,
    list: mirrorNodeDefinitions.schedule.list.buildKey,
  },
  network: {
    exchangeRate: mirrorNodeDefinitions.network.exchangeRate.buildKey,
    fees: mirrorNodeDefinitions.network.fees.buildKey,
    nodes: mirrorNodeDefinitions.network.nodes.buildKey,
    stake: mirrorNodeDefinitions.network.stake.buildKey,
    supply: mirrorNodeDefinitions.network.supply.buildKey,
  },
  balance: {
    list: mirrorNodeDefinitions.balance.list.buildKey,
  },
  block: {
    list: mirrorNodeDefinitions.block.list.buildKey,
    info: mirrorNodeDefinitions.block.info.buildKey,
  },
};
