export const capabilityAudit = {
  ledger: {
    coveredTransactions: [
      "accounts.transfer",
      "accounts.create",
      "accounts.update",
      "accounts.delete",
      "accounts.allowances",
      "accounts.allowances.deleteNft",
      "tokens.create",
      "tokens.mint",
      "tokens.burn",
      "tokens.transfer",
      "tokens.transferNft",
      "tokens.associate",
      "tokens.dissociate",
      "tokens.freeze",
      "tokens.unfreeze",
      "tokens.grantKyc",
      "tokens.revokeKyc",
      "tokens.pause",
      "tokens.unpause",
      "tokens.wipe",
      "tokens.delete",
      "tokens.update",
      "tokens.fees",
      "tokens.airdrop",
      "tokens.claimAirdrop",
      "tokens.cancelAirdrop",
      "tokens.reject",
      "tokens.updateNfts",
      "hcs.create",
      "hcs.update",
      "hcs.delete",
      "hcs.submit",
      "contracts.deploy",
      "contracts.execute",
      "contracts.execute.typed",
      "contracts.delete",
      "contracts.update",
      "files.create",
      "files.append",
      "files.update",
      "files.delete",
      "schedules.create",
      "schedules.sign",
      "schedules.delete",
      "nodes.create",
      "nodes.update",
      "nodes.delete",
      "system.freeze",
      "util.random",
      "batch.atomic",
    ],
    thinTransactions: [
      "nodes.create",
      "nodes.update",
      "nodes.delete",
      "system.freeze",
      "util.random",
    ],
    magicalTransactions: [
      "accounts.transfer",
      "tokens.transfer",
      "contracts.call",
      "contracts.preflight",
      "files.upload",
      "schedules.createIdempotent",
      "tokens.airdrop",
      "batch.atomic",
    ],
    coveredQueries: [
      "transaction.record",
      "transaction.receipt",
      "account.balance",
      "account.info",
      "account.records",
      "token.info",
      "token.nft",
      "topic.info",
      "topic.messages",
      "contract.info",
      "contract.logs",
      "contract.bytecode",
      "contract.simulate",
      "contract.estimate",
      "file.info",
      "file.contents",
      "schedule.info",
      "schedule.wait",
      "network.version",
      "network.addressBook",
      "mirror.*",
    ],
    coveredIds: [
      "AccountId",
      "TokenId",
      "NftId",
      "ContractId",
      "TopicId",
      "ScheduleId",
      "FileId",
      "TransactionId",
      "PendingAirdropId",
      "NodeId",
    ],
    coveredUtilityTypes: [
      "Signer",
      "PrivateKey",
      "PublicKey",
      "Key",
      "FreezeType",
      "ServiceEndpoint",
    ],
  },
  compatibility: {
    namespaceSurfaceRetired: false,
    oneLineFlows: [
      "client.account.send({ to, hbar }).now()",
      "client.token.create({ name, symbol }).now()",
      "client.topic.send({ topicId, message }).now()",
      "client.contract.run({ id, fn, args }).now()",
      "client.file.upload({ contents }).now()",
      "client.token.airdrop({ tokenTransfers }).now()",
      "client.batch.atomic({ txs, batchKey }).now()",
    ],
    preservedUseCases: [
      "accounts",
      "tokens",
      "hcs",
      "contracts",
      "files",
      "schedules",
      "transaction reads",
      "mirror reads",
      "network queries",
    ],
    newlyExposedPower: [
      "token airdrops",
      "token rejection",
      "nft metadata update",
      "node admin",
      "network freeze",
      "prng",
      "atomic batch",
    ],
  },
};
