import * as stylex from "@stylexjs/stylex";

const mobileViewport = "@media (max-width: 640px)";

const tokens = {
  accentBackground: "var(--hieco-wallet-accent-background, #0f172a)",
  accentBackgroundHover: "var(--hieco-wallet-accent-background-hover, #1e293b)",
  accentBorder: "var(--hieco-wallet-accent-border, rgba(14, 116, 144, 0.24))",
  accentForeground: "var(--hieco-wallet-accent-foreground, #f8fafc)",
  accentOutline: "var(--hieco-wallet-accent-border, rgba(14, 116, 144, 0.5))",
  errorBackground: "var(--hieco-wallet-error-background, #fff1f3)",
  errorBorder: "var(--hieco-wallet-error-border, rgba(180, 35, 24, 0.24))",
  errorForeground: "var(--hieco-wallet-error-foreground, #b42318)",
  fontFamily: "var(--hieco-wallet-font-family, inherit)",
  linkHoverBackground: "rgba(148, 163, 184, 0.08)",
  mutedBackground: "var(--hieco-wallet-muted-background, rgba(15, 23, 42, 0.76))",
  mutedBackgroundHover: "var(--hieco-wallet-muted-background-hover, rgba(30, 41, 59, 0.92))",
  mutedBorder: "var(--hieco-wallet-muted-border, rgba(148, 163, 184, 0.32))",
  mutedForeground: "var(--hieco-wallet-muted-foreground, #e2e8f0)",
  overlayBackground: "var(--hieco-wallet-overlay-background, rgba(5, 16, 28, 0.56))",
  radiusCard: "calc(var(--hieco-wallet-radius, 1.25rem) - 0.25rem)",
  radiusDialog: "calc(var(--hieco-wallet-radius, 1.25rem) + 0.25rem)",
  radiusError: "calc(var(--hieco-wallet-radius, 1.25rem) - 0.35rem)",
  radiusPill: "var(--hieco-wallet-radius, 999px)",
  surfaceBackground: "var(--hieco-wallet-surface-background, #ffffff)",
  surfaceBorder: "var(--hieco-wallet-surface-border, rgba(148, 163, 184, 0.24))",
  surfaceShadow: "var(--hieco-wallet-surface-shadow, 0 28px 80px rgba(15, 23, 42, 0.28))",
  textPrimary: "var(--hieco-wallet-text-primary, #0f172a)",
  textSecondary: "var(--hieco-wallet-text-secondary, #475569)",
};

export const walletUiStyles = stylex.create({
  actions: {
    boxSizing: "border-box",
    display: "flex",
    flexDirection: {
      default: "row",
      [mobileViewport]: "column",
    },
    flexWrap: "wrap",
    gap: "0.75rem",
  },
  button: {
    appearance: "none",
    backgroundColor: {
      default: tokens.accentBackground,
      ":focus-visible": tokens.accentBackgroundHover,
      ":hover": tokens.accentBackgroundHover,
    },
    borderColor: tokens.accentBorder,
    borderStyle: "solid",
    borderWidth: "1px",
    color: tokens.accentForeground,
    cursor: {
      default: "pointer",
      ":disabled": "not-allowed",
    },
    opacity: {
      default: 1,
      ":disabled": 0.65,
    },
    transform: {
      default: "translateY(0)",
      ":disabled": "translateY(0)",
      ":focus-visible": "translateY(-1px)",
      ":hover": "translateY(-1px)",
    },
  },
  buttonSecondary: {
    backgroundColor: {
      default: tokens.mutedBackground,
      ":focus-visible": tokens.mutedBackgroundHover,
      ":hover": tokens.mutedBackgroundHover,
    },
    borderColor: tokens.mutedBorder,
    color: tokens.mutedForeground,
  },
  card: {
    backgroundColor: "rgba(248, 250, 252, 0.92)",
    borderColor: tokens.mutedBorder,
    borderRadius: tokens.radiusCard,
    borderStyle: "solid",
    borderWidth: "1px",
    boxSizing: "border-box",
    padding: "1rem",
  },
  centeredStack: {
    boxSizing: "border-box",
    justifyItems: "center",
    textAlign: "center",
  },
  desktopSection: {
    borderTopColor: tokens.surfaceBorder,
    borderTopStyle: "solid",
    borderTopWidth: "1px",
    boxSizing: "border-box",
    display: "grid",
    gap: "0.75rem",
    paddingTop: "1rem",
  },
  copy: {
    boxSizing: "border-box",
    color: tokens.textSecondary,
    fontSize: "0.95rem",
    lineHeight: 1.5,
    margin: 0,
  },
  dialog: {
    backgroundColor: tokens.surfaceBackground,
    borderColor: tokens.surfaceBorder,
    borderRadius: tokens.radiusDialog,
    borderStyle: "solid",
    borderWidth: "1px",
    boxShadow: tokens.surfaceShadow,
    boxSizing: "border-box",
    color: tokens.textPrimary,
    display: "grid",
    fontFamily: tokens.fontFamily,
    gap: "1rem",
    maxWidth: "34rem",
    padding: {
      default: "1.25rem",
      [mobileViewport]: "1rem",
    },
    width: "100%",
  },
  error: {
    backgroundColor: tokens.errorBackground,
    borderColor: tokens.errorBorder,
    borderRadius: tokens.radiusError,
    borderStyle: "solid",
    borderWidth: "1px",
    boxSizing: "border-box",
    color: tokens.errorForeground,
    padding: "0.9rem 1rem",
  },
  focusRing: {
    outline: {
      default: "none",
      ":focus-visible": `2px solid ${tokens.accentOutline}`,
    },
    outlineOffset: {
      default: "0",
      ":focus-visible": "2px",
    },
  },
  header: {
    alignItems: "flex-start",
    boxSizing: "border-box",
    display: "flex",
    flexDirection: {
      default: "row",
      [mobileViewport]: "column",
    },
    gap: "1rem",
    justifyContent: "space-between",
  },
  interactive: {
    alignItems: "center",
    borderRadius: tokens.radiusPill,
    boxSizing: "border-box",
    display: "inline-flex",
    fontFamily: tokens.fontFamily,
    fontSize: "0.95rem",
    fontWeight: 600,
    gap: "0.5rem",
    justifyContent: "center",
    lineHeight: 1.2,
    minHeight: "2.75rem",
    padding: "0.75rem 1rem",
    textDecoration: "none",
    transition:
      "background-color 160ms ease, border-color 160ms ease, color 160ms ease, transform 160ms ease, opacity 160ms ease",
    width: {
      default: "auto",
      [mobileViewport]: "100%",
    },
  },
  link: {
    backgroundColor: {
      default: "transparent",
      ":focus-visible": tokens.linkHoverBackground,
      ":hover": tokens.linkHoverBackground,
    },
    borderColor: tokens.mutedBorder,
    borderStyle: "solid",
    borderWidth: "1px",
    color: tokens.textPrimary,
    cursor: "pointer",
    transform: {
      default: "translateY(0)",
      ":focus-visible": "translateY(-1px)",
      ":hover": "translateY(-1px)",
    },
  },
  overlay: {
    backgroundColor: tokens.overlayBackground,
    boxSizing: "border-box",
    display: "grid",
    inset: 0,
    padding: "1rem",
    placeItems: "center",
    position: "fixed",
    zIndex: 1000,
  },
  qr: {
    backgroundColor: "#ffffff",
    borderColor: tokens.mutedBorder,
    borderRadius: "1rem",
    borderStyle: "solid",
    borderWidth: "1px",
    boxSizing: "border-box",
    height: "auto",
    maxWidth: "100%",
    width: "16rem",
  },
  qrSection: {
    background:
      "linear-gradient(180deg, rgba(248, 250, 252, 0.98) 0%, rgba(241, 245, 249, 0.92) 100%)",
    borderColor: "rgba(14, 116, 144, 0.16)",
    borderRadius: tokens.radiusCard,
    borderStyle: "solid",
    borderWidth: "1px",
    boxSizing: "border-box",
    display: "grid",
    gap: "0.75rem",
    justifyItems: "center",
    padding: {
      default: "1.25rem",
      [mobileViewport]: "1rem",
    },
    textAlign: "center",
  },
  stackSm: {
    boxSizing: "border-box",
    display: "grid",
    gap: "0.5rem",
  },
  title: {
    boxSizing: "border-box",
    color: tokens.textPrimary,
    fontSize: "1rem",
    fontWeight: 700,
    margin: 0,
  },
  wallet: {
    backgroundColor: "rgba(248, 250, 252, 0.92)",
    borderColor: tokens.mutedBorder,
    borderRadius: tokens.radiusCard,
    borderStyle: "solid",
    borderWidth: "1px",
    boxSizing: "border-box",
    display: "grid",
    gap: "0.75rem",
    padding: "0.95rem 1rem",
  },
  walletCopy: {
    boxSizing: "border-box",
    display: "grid",
    gap: "0.5rem",
    minWidth: 0,
  },
  walletHeader: {
    alignItems: "center",
    boxSizing: "border-box",
    display: "flex",
    gap: "0.75rem",
  },
  walletIcon: {
    boxSizing: "border-box",
    flexShrink: 0,
    height: "1.75rem",
    objectFit: "contain",
    width: "1.75rem",
  },
  walletList: {
    boxSizing: "border-box",
    display: "grid",
    gap: "0.75rem",
  },
  walletMeta: {
    boxSizing: "border-box",
    color: tokens.textSecondary,
    fontSize: "0.95rem",
    lineHeight: 1.45,
    margin: 0,
  },
});
